// Code generated by protoc-gen-go.
// source: github.com/chazsmi/stock-service/proto/stock.proto
// DO NOT EDIT!

/*
Package stock is a generated protocol buffer package.

It is generated from these files:
	github.com/chazsmi/stock-service/proto/stock.proto

It has these top-level messages:
	StockRequest
	StockReadResponse
	StockWriteResponse
*/
package stock

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StockRequest struct {
	Sku    string `protobuf:"bytes,1,opt,name=sku" json:"sku,omitempty"`
	Amount int32  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *StockRequest) Reset()                    { *m = StockRequest{} }
func (m *StockRequest) String() string            { return proto.CompactTextString(m) }
func (*StockRequest) ProtoMessage()               {}
func (*StockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StockReadResponse struct {
	Sku    string `protobuf:"bytes,1,opt,name=sku" json:"sku,omitempty"`
	Amount int32  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *StockReadResponse) Reset()                    { *m = StockReadResponse{} }
func (m *StockReadResponse) String() string            { return proto.CompactTextString(m) }
func (*StockReadResponse) ProtoMessage()               {}
func (*StockReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StockWriteResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *StockWriteResponse) Reset()                    { *m = StockWriteResponse{} }
func (m *StockWriteResponse) String() string            { return proto.CompactTextString(m) }
func (*StockWriteResponse) ProtoMessage()               {}
func (*StockWriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*StockRequest)(nil), "StockRequest")
	proto.RegisterType((*StockReadResponse)(nil), "StockReadResponse")
	proto.RegisterType((*StockWriteResponse)(nil), "StockWriteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Stock service

type StockClient interface {
	Check(ctx context.Context, in *StockRequest, opts ...client.CallOption) (*StockReadResponse, error)
	Update(ctx context.Context, in *StockRequest, opts ...client.CallOption) (*StockWriteResponse, error)
}

type stockClient struct {
	c           client.Client
	serviceName string
}

func NewStockClient(serviceName string, c client.Client) StockClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "stock"
	}
	return &stockClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *stockClient) Check(ctx context.Context, in *StockRequest, opts ...client.CallOption) (*StockReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Stock.Check", in)
	out := new(StockReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockClient) Update(ctx context.Context, in *StockRequest, opts ...client.CallOption) (*StockWriteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Stock.Update", in)
	out := new(StockWriteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Stock service

type StockHandler interface {
	Check(context.Context, *StockRequest, *StockReadResponse) error
	Update(context.Context, *StockRequest, *StockWriteResponse) error
}

func RegisterStockHandler(s server.Server, hdlr StockHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Stock{hdlr}, opts...))
}

type Stock struct {
	StockHandler
}

func (h *Stock) Check(ctx context.Context, in *StockRequest, out *StockReadResponse) error {
	return h.StockHandler.Check(ctx, in, out)
}

func (h *Stock) Update(ctx context.Context, in *StockRequest, out *StockWriteResponse) error {
	return h.StockHandler.Update(ctx, in, out)
}

func init() { proto.RegisterFile("github.com/chazsmi/stock-service/proto/stock.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xce, 0x48, 0xac, 0x2a, 0xce, 0xcd, 0xd4, 0x2f,
	0x2e, 0xc9, 0x4f, 0xce, 0xd6, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2f, 0x28, 0xca,
	0x2f, 0xc9, 0x87, 0x88, 0xe9, 0x81, 0xd9, 0x4a, 0x16, 0x5c, 0x3c, 0xc1, 0x20, 0x6e, 0x50, 0x6a,
	0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x00, 0x17, 0x73, 0x71, 0x76, 0xa9, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x67, 0x10, 0x88, 0x29, 0x24, 0xc6, 0xc5, 0x96, 0x98, 0x9b, 0x5f, 0x9a, 0x57, 0x22, 0xc1,
	0x04, 0x14, 0x64, 0x0d, 0x82, 0xf2, 0x94, 0x6c, 0xb9, 0x04, 0xa1, 0x3a, 0x13, 0x53, 0x82, 0x52,
	0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x49, 0xd0, 0xae, 0xc7, 0x25, 0x04, 0xd6, 0x1e, 0x5e, 0x94,
	0x59, 0x92, 0x0a, 0xd7, 0x2f, 0xc1, 0xc5, 0x5e, 0x5c, 0x9a, 0x9c, 0x9c, 0x5a, 0x5c, 0x0c, 0x36,
	0x83, 0x23, 0x08, 0xc6, 0x35, 0x4a, 0xe5, 0x62, 0x05, 0xab, 0x17, 0xd2, 0xe1, 0x62, 0x75, 0xce,
	0x48, 0x05, 0x32, 0x78, 0xf5, 0x90, 0x5d, 0x2e, 0x25, 0xa4, 0x87, 0xe1, 0x1c, 0x25, 0x06, 0x21,
	0x3d, 0x2e, 0xb6, 0xd0, 0x82, 0x94, 0xc4, 0x92, 0x54, 0x74, 0xe5, 0xc2, 0x7a, 0x98, 0xd6, 0x2b,
	0x31, 0x24, 0xb1, 0x81, 0x83, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x04, 0x8f, 0x4f,
	0x4c, 0x01, 0x00, 0x00,
}
